version: "3.9"
services:
    backend:
        build: .
        container_name: restaurants-backend
        ports:
            - "8080:8080"
        env_file:
            - .env
        restart: always
