version: "3.9"
services:
  backend:
    build: .
    container_name: restaurants-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  data:
